package com.nhdasystem.util;

public enum ModuleList {
    EMPLOYEE, USER, PRIVILAGE, DESIGNATION, USERPASSWORDCHANGE, CLIENT,GURANTOR,EMPLOYEESTATUS,CLIENTSTATUS
    ,WORKINGSTATUS,LOANPURPOSE,CIVILSTATUS,BRANCH,GNDIVISION,DSDIVISION,DISTRICT,PROVINCE,LOAN,LOANSTATUS
    ,LOANTYPESTATUS,LOANCATEGORY,LOANTYPE,LOANPAYMENTSTATUS,LOANPAYMENT,PROPERTY,CRITERIA,CONSTRAINT,PROPERTYSTATUS,
    ROLE,USERSTATUS
}
